### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by CaptainRexPL**
1. Now you can download the latest Parrot's build from github actions
2. Added dependabot to keep dependencies up-to-date
3. Now when Parrot sends a message from the input channel to the output channel it will also send a message ```Message has been sent to channel <#{output channel's ID}>``` so you are 100% that the output channel's ID is correct. I made sure that this won't make an infinite loop.

Most of the commits are just my tests on github actions so they don't matter.

### CODE REVIEW

**Comment by Signam** [comment]
Lgtm! Make the output message ("Message has been sent to <") an option in the config file. Also, if you wish to see these changes being made in 5c, you will have to ask rfresh#2222 as I don't use discord or play minecraft anymore

**Comment by CaptainRexPL** [comment]
Alright, now you can toggle the debug message.

**Comment by CaptainRexPL** [comment]
Now instead of normal messages there will be embedded ones. 
To send an image between channels you have to write a message that mentions the bot (the message with bot mention will not get relayed) and the image (it can't be a link to the image or else it won't work).

**Comment by Signam** [comment]
Thank u Dr. Fresh

**Pull request merged**
